### ISSUE TITLE
Linked URL after launching an experiment

### ISSUE THREAD

**Issue by mirkospasic** [hobbit-project/platform#154] opened 2017-11-14 10:50 UTC
It looks like the URL that is linked when a new experiment has been started does not work any more. It contains "experiment/details?id=123" instead of "experiment/123".

**Comment by MichaelRoeder** [comment] 2017-11-14 10:59
My description has screenshots! See #155  :stuck_out_tongue_winking_eye:

**Comment by Ennosigaeon** [comment] 2017-11-14 12:29
Duplicate of #155 .

**Closed by Ennosigaeon** 2017-11-14 12:29 UTC
