### ISSUE TITLE
Created challenge tasks start with already registered systems

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#139] opened 2017-11-02 11:04 UTC
## Problem

When a user wants to register a system for a challenge, all systems that fit are marked with a checkmark. However, when the user accepts this, the GUI does not store the changes.

## Solution

I think that is a simply problem that came up in the discussion from https://github.com/hobbit-project/platform/pull/126#issuecomment-337283043 on. We first wanted to check all systems that fit to the task but later on we decided to ask the backend for the current registrations. I am afraid that the current implementation in the [`tmp-develop`](https://github.com/hobbit-project/platform/tree/tmp-develop) branch is a mixture of both.

This should be changed to show only the currently registered systems.

**Comment by Ennosigaeon** [comment] 2017-11-02 12:03
Can we please first fix the [develop](https://github.com/hobbit-project/platform/tree/develop) branch before resolving new issues? I think we make our life unneccessary complicated by introducing new commits.

**Comment by MichaelRoeder** [comment] 2017-11-02 12:35
@Ennosigaeon we have to release a new version of the platform ASAP. So we decided to move the current development into the [`tmp-develop`](https://github.com/hobbit-project/platform/tree/) branch, fix the most important bugs and release the next version. 

Moving on in this branch shouldn't make it more complicated for you to delete the faulty commits in develop, right?

**Comment by Ennosigaeon** [comment] 2017-11-02 12:49
Looking at the history of that branch, it seems like the master was sucessfully merged. What exactly is the reason to keep this branch besides the normal develop?

**Comment by MichaelRoeder** [comment] 2017-11-02 12:59
As far as I see, the problem from https://github.com/hobbit-project/platform/pull/130#issuecomment-339896586 has not been fixed until now since the merge hasn't been rolled back.

**Comment by Ennosigaeon** [comment] 2017-11-03 10:31
I had a look at this issue using the current tmp-develop branch and I am not able to reproduce the reported behaviour. I have openend a challenge (DEBS GC Test2) and checked the current registrations. There are two systems registered for both tasks. Next I went to "Register System" and for both tasks the correct two systems were checked. It is possible to unsubsribe both systems (checked via no systems displayed "Show Registrations" and no ticks at "Register System") and to subscribe systems again (again checked via "Show Registrations" with the correct systems listed and both systems ticked at "Register System").

**Comment by MichaelRoeder** [comment] 2017-11-03 12:21
@Ennosigaeon thanks for checking. You are right, the problem is not the registration itself. During the creation of a challenge task, the platform already registers systems (which is a wrong behavior).

The following SPARQL INSERT query has been sent to the storage while creating a new task. It can be seen, that it already contains the registration of two systems although the task has just been created (and nobody had the chance to register a system).
```
PREFIX  hobbit: <http://w3id.org/hobbit/vocab#> 
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX  chal: <http://w3id.org/hobbit/challenges#>  

WITH <http://hobbit.org/graphs/ChallengeDefinitions> 
INSERT {
   chal:cc48752a-c0bd-44bd-86c8-65b8a1738917_task2 rdf:type hobbit:ChallengeTask .
   chal:cc48752a-c0bd-44bd-86c8-65b8a1738917_task2 rdfs:label "Second Linking Task"@en .
   chal:cc48752a-c0bd-44bd-86c8-65b8a1738917_task2 rdfs:comment "just another linking task"@en .
   chal:cc48752a-c0bd-44bd-86c8-65b8a1738917_task2 hobbit:involvesBenchmark <http://w3id.org/bench#Linking> .
   chal:cc48752a-c0bd-44bd-86c8-65b8a1738917_task2 hobbit:isTaskOf chal:cc48752a-c0bd-44bd-86c8-65b8a1738917 .
   ...
   chal:cc48752a-c0bd-44bd-86c8-65b8a1738917_task2 hobbit:involvesSystemInstance <http://w3id.org/system#amlLinking> .
   chal:cc48752a-c0bd-44bd-86c8-65b8a1738917_task2 hobbit:involvesSystemInstance <http://w3id.org/system#limesV2> .
   <http://w3id.org/bench#precision> rdf:type hobbit:KPI .
   ... 
} WHERE   {} >
```

**Comment by MichaelRoeder** [comment] 2017-11-03 12:54
I went through the process of the task creation and tried to debug the behavior of the platform. When the user chooses a benchmark for the challenge task, the GUI is loading the information about the benchmark from the backend.

The example user has chosen the Platform Benchmark and the GUI calls
```
http://localhost:8080/rest/benchmarks/http%3A%2F%2Fw3id.org%2Fhobbit%2Fplatform-benchmark%2Fvocab%23PlatformBenchmark
```
The response contains the following data including systems the user could benchmark
```json
{
    "type":"benchmarkBean",
    "description":"This benchmark emulates the traffic created by benchmarking a SPARQL store to determine the maximal throughput of the platform.",
    "id":"http://w3id.org/hobbit/platform-benchmark/vocab#PlatformBenchmark",
    "name":"HOBBIT Platform Benchmark",
    "configurationParamNames":[...],
    "configurationParams":[...],
    "kpis":[...],
    "systems":[
        {
            "description":"The system needed to run the platform benchmark instantiating 1 system adapter.",
            "id":"http://w3id.org/hobbit/platform-benchmark/vocab#PlatformBenchSystem_1",
            "name":"HOBBIT Platform Benchmark System 1"
        },{
            "description":"The system needed to run the platform benchmark instantiating 2 system adapters.",
            "id":"http://w3id.org/hobbit/platform-benchmark/vocab#PlatformBenchSystem_2",
            "name":"HOBBIT Platform Benchmark System 2"
        },{
            "description":"The system needed to run the platform benchmark instantiating 3 system adapters.",
            "id":"http://w3id.org/hobbit/platform-benchmark/vocab#PlatformBenchSystem_3",
            "name":"HOBBIT Platform Benchmark System 3"
        }
    ]
}
```

When the user stores the created task, the complete challenge bean is sent to the backend and the backend stores the difference of the bean with the data loaded from the storage. It can be seen that the benchmark still contains the information about the systems.
```json
{
  "id": "http://w3id.org/hobbit/challenges#cc48752a-c0bd-44bd-86c8-65b8a1738917",
  "name": "Linking Test Challenge",
  "description": "This is only a test challenge for testing :D",
  "organizer": "gerbil",
  "executionDate": "2017-11-21T00:00Z",
  "publishDate": "2017-11-30T00:00Z",
  "visible": true,
  "closed": false,
  "tasks": [
    {
      "id": "http://w3id.org/hobbit/challenges#cc48752a-c0bd-44bd-86c8-65b8a1738917_task1",
      "name": "Linking",
      "description": "A linking task",
      ...
    },
    {
      "id": "http://w3id.org/hobbit/challenges#cc48752a-c0bd-44bd-86c8-65b8a1738917_task2",
      "name": "Second Linking Task",
      "description": "just another linking task",
      ...
    },
    {
      "id": "http://w3id.org/hobbit/challenges#cc48752a-c0bd-44bd-86c8-65b8a1738917_task3",
      "name": "test task 3",
      "description": "task 3",
      "benchmark": {
        "id": "http://w3id.org/hobbit/platform-benchmark/vocab#PlatformBenchmark",
        "name": "HOBBIT Platform Benchmark",
        "description": "This benchmark emulates the traffic created by benchmarking a SPARQL store to determine the maximal throughput of the platform.",
        "type": "benchmarkBean",
        "configurationParamNames": [
          ...
        ],
        "configurationParams": [
          ...
        ],
        "kpis": [
          ...
        ],
        "systems": [
          {
            "id": "http://w3id.org/hobbit/platform-benchmark/vocab#PlatformBenchSystem_1",
            "name": "HOBBIT Platform Benchmark System 1",
            "description": "The system needed to run the platform benchmark instantiating 1 system adapter."
          },
          {
            "id": "http://w3id.org/hobbit/platform-benchmark/vocab#PlatformBenchSystem_2",
            "name": "HOBBIT Platform Benchmark System 2",
            "description": "The system needed to run the platform benchmark instantiating 2 system adapters."
          },
          {
            "id": "http://w3id.org/hobbit/platform-benchmark/vocab#PlatformBenchSystem_3",
            "name": "HOBBIT Platform Benchmark System 3",
            "description": "The system needed to run the platform benchmark instantiating 3 system adapters."
          }
        ]
      },
      "configurationParams": [
        ...
      ]
    }
  ],
  "type": "challengeBean"
}
```
This list of systems is interpreted as system registrations in the backend (https://github.com/hobbit-project/platform/blob/master/hobbit-gui/gui-serverbackend/src/main/java/de/usu/research/hobbit/gui/rabbitmq/RdfModelCreationHelper.java#L143-L146).

@Ennosigaeon I see two ways to fix this bug. 
1. The front end client removes the list of systems when it recieves the benchmark data requested for the challenge task.
2. We change the interpretation of the benchmark bean inside the challenge task bean to ignore the list of systems. But I am not sure whether this influences other parts of the backend.

**Comment by Ennosigaeon** [comment] 2017-11-03 13:26
It should be no problem to drop the systems if a user creates a new task. Let me check that later and I will tell you if there are any concerns from my side.

**Comment by Ennosigaeon** [comment] 2017-11-06 08:55
It is no problem to simply remove all systems in the BenchmarkBean before saving the new task. Fix is pushed.

**Closed** 2017-11-07 12:45 UTC
Labels: component: UI, priority: critical, type: bug
