### ISSUE TITLE
When viewing/editing a challenge task, default configuration parameters are always used

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#301] opened 2018-05-14 12:47 UTC
Instead of actual values from backend for benchmark parameters, it looks like default ones are always displayed in input fields.

https://master.project-hobbit.eu/challenges/http:%2F%2Fw3id.org%2Fhobbit%2Fchallenges%23b37bf554-33a1-416a-8e7d-61879f920249/edit/http:%2F%2Fw3id.org%2Fhobbit%2Fchallenges%23b37bf554-33a1-416a-8e7d-61879f920249_task1

**Comment by denkv** [comment] 2018-05-14 13:01
Sometimes there are just empty fields. Server's response actually contains related values.

https://master.project-hobbit.eu/challenges/http:%2F%2Fw3id.org%2Fhobbit%2Fchallenges%23b37bf554-33a1-416a-8e7d-61879f920249/edit/http:%2F%2Fw3id.org%2Fhobbit%2Fchallenges%23b37bf554-33a1-416a-8e7d-61879f920249_task2

But this is probably just https://github.com/hobbit-project/platform/issues/201

**Comment by denkv** [comment] 2018-05-14 13:03
@Ennosigaeon does https://github.com/hobbit-project/platform/pull/282 fix this?

**Comment by Ennosigaeon** [comment] 2018-05-14 13:56
@denkv Yes, this is a duplicate of #201 which is already fixed in PR #282. It could also be the fix for #200, but I am not totally sure about that one.

**Comment by smirnp** [comment] 2018-05-17 15:35
GUI modifies the challengeDefinitions, but if challenge already has public results - the GUI uses them for representation. But all modifications still to go challengeDefinitions

**Comment by denkv** [comment] 2018-05-18 08:07
That happened for a challenge that was not yet executed or published (entirely in ChallengeDefinitions graph), and responses from gui-serverbackend contained right values. Looks like linked PR resolves this.

**Closed** 2018-10-26 09:57 UTC
Labels: component: UI, priority: high, type: bug
