### ISSUE TITLE
involvesSystemInstance triples are created with the task, and not with system registration

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#141] opened 2017-11-03 11:45 UTC
`task hobbit:involvesSystemInstance system` data is already there when task just was created and they're not added when system registration is done.

**Comment by MichaelRoeder** [comment] 2017-11-03 13:26
Duplicate of 139 which includes a more detailed description of the problem. Will close this ticket.

**Closed by MichaelRoeder** 2017-11-03 13:26 UTC
Labels: resolution: duplicate
