### ISSUE TITLE
Allow benchmarks to provide custom experiment status messages

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#473] opened 2019-10-12 23:08 UTC
Currently we have generic HOBBIT-provided messages like "Benchmark and system are initializing". We can allow benchmarks to provide custom status messages.

### Solutions
* benchmark sends a predefined command to the command queue, which includes status message and maybe other details
* we display the most recent log line which adheres to some agreed rule (maybe with a text like "Status: ..." or using other attributes of the log event)

**Comment by MichaelRoeder** [comment] 2019-10-15 10:45
Duplicate of #119. Please update the already existing issue and close this one.

**Closed** 2019-10-20 14:39 UTC
Labels: resolution: duplicate, type: enhancement
