### ISSUE TITLE
Challenge homepage URL

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#164] opened 2017-11-17 12:18 UTC
Add separate entry and display for challenge homepage or information URL.

- [x] look for existing property which could express this (in Dublin core DCTerms?)
- [x] display link on challenge page
- [x] entry field when adding or editing a challenge

**Comment by Ennosigaeon** [comment] 2018-01-22 10:59
I am not sure, what I am supposed to do here...

**Comment by MichaelRoeder** [comment] 2018-01-23 11:43
I have added the `homepage` attribute to the [`ChallengeBean`](https://github.com/hobbit-project/platform/blob/feature/challengeHomepage/hobbit-gui/gui-serverbackend/src/main/java/de/usu/research/hobbit/gui/rest/beans/ChallengeBean.java#L33). The owner/creator of a challenge should be able to set it (or change it when editing). Other users should simply see the homepage (if it is available) as link, e.g., to the homepage of the challenge.

This feature is implemented in the `feature/challengeHomepage` branch.

**Comment by MichaelRoeder** [comment] 2018-01-23 11:51
We will use [`foaf:homepage`](http://xmlns.com/foaf/spec/#term_homepage) as property.

**Comment by Ennosigaeon** [comment] 2018-01-31 13:50
I have added both the possibility to edit the homepage url and display the url. However, there seems to be a problem with storing the url:

`www.challenge.de` is transformed to `file:///usr/src/app/www.challenge.de` while `http://www.challenge.de` is stored correctly.

**Comment by MichaelRoeder** [comment] 2018-01-31 18:43
@Ennosigaeon the problem should be fixed.

**Comment by Ennosigaeon** [comment] 2018-02-01 12:41
@MichaelRoeder I can confirm that this issue is fixed. From my point of view is issue is ready to be merged.

**Closed** 2018-02-06 08:30 UTC
Labels: component: UI, priority: low, type: enhancement
