### ISSUE TITLE
Save button during editing the challenge

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#192] opened 2018-01-10 10:02 UTC
I have created the challenge, then decided to edit execution date, but cannot see save button. 
https://gyazo.com/72ddbda8d5da324205a042b61b634c87
Is it allowed to do that? 
Thank you!

**Comment by MichaelRoeder** [comment] 2018-01-10 10:16
Duplicate of #166

**Closed** 2018-01-18 15:36 UTC
Labels: resolution: duplicate
